#include "headfile.h"

extern unsigned char chalu_flag;
extern unsigned char end_count;
extern unsigned char chalu_dirction;
extern unsigned char chalu_turn_time;
extern Maiy_2_dimensional TpM;
extern Maiy_2_dimensional TpL;
extern Maiy_2_dimensional TpR;
extern Maiy_2_dimensional LMaxPoint;
extern Maiy_2_dimensional RMaxPoint;
extern Maiy_2_dimensional TEM_L;
extern uint8 cnt_fache1;
extern Maiy_2_dimensional TEM_R;
extern uint8 RFixLineFlag;
extern int16   RFixLineStart;
extern uint8  LFixLineFlag;
extern uint8 one_add;
extern int16 one_add_time;
extern Maiy_2_dimensional ColPoint_L;
extern Maiy_2_dimensional ColPoint_R;
extern int16  LFixLineStart;
extern int LLineSegmentST[10];
extern int LLineSegmentEN[10];
extern int  RLineSegmentST[10];
extern int RLineSegmentEN[10];
 extern uint8 fork_road;
 extern int LLineSegmentCnt;
 extern int RLineSegmentCnt;
 extern int16 tLCnt;
 extern int16 tRCnt;
 extern int16 tMCnt;
 extern int LColCnt;
 extern int RColCnt;
 extern int16 TriangRange[160];
 extern uint8 sancha_flag_left;
 extern uint8 sancha_flag_right;
 extern uint8 diu_flag1;
 extern uint8 diu_flag2;
 extern _Bool ForkLeft;
 extern _Bool ForkRight;
 extern uint8 jilu;
 extern uint8 flag22;
 extern uint8 cnt_fache1;
 extern uint16 cnt_black;
 extern uint16 sancha_stop;
 extern uint16 sanchacount;
 extern int16 cnt_1;
 extern int16 cnt_2;
 extern int16 cnt_11;
 extern int16 cnt_22;
 extern uint8 yes;
 extern Maiy_2_dimensional LowLeftJump;
 extern Maiy_2_dimensional LowRightJump;
 extern  int16 point;
// extern  uint8 maxflag;
// extern   uint16 maxvalue;
 extern  uint8 ForkStep;
 extern Maiy_2_dimensional TriangBlackPoint;
 extern  uint8 sancha_flag1;
 extern uint8 nowait;
void chalu();
void ShangCha_flo_law(Maiy_characteristic_point* sc_char);
void ALL_fill(Maiy_characteristic_point* sc_char);
void sec_fork_law(Maiy_characteristic_point *SewFork_char);
void ShangCha(Maiy_characteristic_point* sc_char);
void ShangCha_thr_law(Maiy_characteristic_point* sc_char);
void ShangCha_fiv_law(Maiy_characteristic_point* sc_char);
